### ISSUE TITLE
Magnetic sensor 

### ISSUE THREAD

**Issue by Coldz0** [omarreis/FiremonkeySensorFusion#1]
magnetic sensor doesnt work, values x, y ,z keeps at 0
Tested in Delphi10.3.2 , Android 9

**Comment by omarreis** [comment]
Recent Android versions require apps to request permissions to use device sensors.  This is not implemented in the sample at this time.  May be the sensor permissions are not set.
See https://github.com/omarreis/BoatAttitude/blob/master/fBoatAttitude2.pas for an example of how to request permissons using DelphiWorlds requester.

You can also set the app permissions manually on Android Config, for testing purposes

**Comment by omarreis** [comment]
Changed sample app code to include permissions request for Android
