### ISSUE TITLE
App crashes after ~20 sec

### ISSUE THREAD

**Issue by Gregory667** [omarreis/FiremonkeySensorFusion#2]
Compiled with Delphi 10.4 for Android 32 Bit.
Device is a Samsung Galaxy S8 (Android 9)

After starting the App, it works for ~20sec. In this time it shows the sensors data. 
Then it crashes without a message and closing.

Even if i comment the onXXXXChange events it crashes.

**Comment by haughtiant** [comment]
me too!

**Comment by DelphiWorlds** [comment]
Please change the TPlatformSensor.SensorChanged method in DW.Sensor.Android.pas to:

```
procedure TPlatformSensor.SensorChanged(const event: JSensorEvent);
var
  LValues: TSensorValues;
  I: Integer;
  LMillis: Int64;
  LEventValues: TJavaArray<Single>;
begin
  LEventValues := event.values;
  try
    SetLength(LValues, LEventValues.Length);
    for I := 0 to LEventValues.Length - 1 do
      LValues[I] := LEventValues[I];
  finally
    LEventValues.Free;
  end;
  if FTimestamp = 0 then
  begin
    FSensorStart := Now;
    LMillis := 0;
  end
  else
    LMillis := (event.timestamp - FTimestamp) div 1000000;
  ValuesChanged(LValues, IncMilliSecond(FSensorStart, LMillis));
end;
```

**Comment by haughtiant** [comment]
Thank you very much! Thanks David Nottage !

**Comment by Gregory667** [comment]
Also a big thank you from me, it works great.

**Comment by omarreis** [comment]
This seems to be a new problem, caused by a JNI memory leak on SensorChanged event.
When the allocation table reaches a certain size ( 52 k allocations) the app is terminated by the OS.
As pointed by Dave Nottage above, calling LEventValues.Free fixes the issue.

**Comment by omarreis** [comment]
Also note that on Delphi 10.4.1 you cannot start the location sensor from FormActivate on iOS. 
The sensor feed will not start.
I fixed that by activating the sensors from a 2 seconds Timer.
